house_finder/house_finder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from houses.views import HousesListView

urlpatterns = [
    url(r'^$', HousesListView.as_view(), name='index'),
    url(r'^houses/', include('houses.urls')),
    url(r'^admin/', admin.site.urls),
]

house_finder/houses/urls.py
"""
To design URLs for an app, you create a Python module informally called a URLconf (URL configuration).
This module is pure Python code and is a mapping between URL path expressions to Python functions
(your views).

This mapping can be as short or as long as needed. It can reference other mappings. And, because
it’s pure Python code, it can be constructed dynamically.
"""
from django.conf.urls import url

from . import views

app_name = 'houses'

urlpatterns = [
    url(r'^$', views.HousesListView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/detail', views.DetailView.as_view(), name='detail'),
]

house_finder/houses/models.py
"""
A model is the single, definitive source of information about your data. It contains the essential
fields and behaviors of the data you’re storing. Generally, each model maps to a single database
table.
"""
from django.db import models


class HousesProvider(models.Model):
    """Real state web site to crawl"""
    name = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return self.name


class City(models.Model):
    """City name"""
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'cities'

    def __str__(self):
        return self.name


class District(models.Model):
    """District of a city"""
    name = models.CharField(max_length=150)
    city = models.ForeignKey(City, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Neighborhood(models.Model):
    """Neighborhood of a district"""
    name = models.CharField(max_length=150)
    district = models.ForeignKey(District, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class StartURL(models.Model):
    """Initial url to begin the crawling"""
    TYPE = (('R', 'Rent'),
            ('B', 'Buy'))
    city = models.ForeignKey(City, null=False, on_delete=models.PROTECT)
    district = models.ForeignKey(District, null=True, on_delete=models.SET_NULL)
    neighborhood = models.ForeignKey(Neighborhood, null=True, on_delete=models.SET_NULL)
    provider = models.ForeignKey(HousesProvider)
    type = models.CharField(max_length=1, choices=TYPE, default='R')
    url = models.URLField(unique=True)

    def __str__(self):
        return '{0} - {1} - {2} - {3}'.format(self.provider, self.city, self.district, self.neighborhood)


class House(models.Model):
    """House definition"""

    TITLE_MAX_LENGTH = 500

    site_id = models.CharField(max_length=100)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    description = models.TextField(default=None)
    price = models.IntegerField(null=True)
    url = models.URLField(unique=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    sqft_m2 = models.IntegerField(null=True)
    rooms = models.IntegerField(null=True)
    baths = models.IntegerField(null=True)
    article_update_date = models.CharField(max_length=100)
    is_interesting = models.BooleanField(default=False)
    is_discard = models.BooleanField(default=False)
    has_seen = models.BooleanField(default=False)
    notes = models.TextField(default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=False)
    last_view_at = models.DateTimeField(auto_now=True)
    start_url = models.ForeignKey(StartURL, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    @property
    def provider(self):
        """
        Get the provider name
        :return: provider name
        :rtype: str
        """
        if self.start_url:
            return self.start_url.provider.name.title()
        else:
            return 'Link'

house_finder/store_houses/models.py
from django.db import models


class House(models.Model):
    site_id = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    neighborhood = models.CharField(max_length=100)
    description = models.TextField(default=None)
    price = models.IntegerField(null=True)
    url = models.URLField(unique=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    sqft_m2 = models.IntegerField()
    rooms = models.IntegerField()
    baths = models.IntegerField()
    article_update_date = models.CharField(max_length=100)
    is_interesting = models.BooleanField(default=False)
    is_discard = models.BooleanField(default=False)
    has_seen = models.BooleanField(default=False)
    notes = models.TextField(default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('site_id', 'website',)

house_finder/houses/views.py
"""
A view function, or view for short, is simply a Python function that takes a Web request
and returns a Web response.
This response can be the HTML contents of a Web page, or a redirect, or a 404 error, or an
XML document, or an image . . . or anything, really. The view itself contains whatever
arbitrary logic is necessary to return that response.
"""
from django.views import generic
from django_filters.views import FilterView
from django_tables2 import SingleTableView

from .models import House
from .tables import HouseTable
from .filters import HouseFilter


class HousesListView(FilterView, SingleTableView):
    """View for a list of houses with filtering"""
    model = House
    template_name = 'houses/houses_list2.html'
    context_object_name = 'houses'
    ordering = ['price']
    filterset_class = HouseFilter
    table_class = HouseTable

    def get_context_data(self, **kwargs):
        """Filter the base data to be shown"""
        context = super(HousesListView, self).get_context_data(**kwargs)
        context['rent'] = House.objects.filter(start_url__type__exact='R')
        return context


class DetailView(generic.DetailView):
    """View of the details of a house"""
    model = House
    template_name = 'houses/detail.html'
    model.has_seen = True

house_finder/houses/templates/houses/detail.html
{% extends "houses/master.html" %}

{% block content %}
<h1>{{ house.title }}</h1>
    <div class="house-price">Price: {{ house.price }} €</div>
    <div class="house-url">Url: <a href="{{ house.url }}">{{ house.website }}</a></div>
    <div class="house-sqft_m2">Surface: {{ house.sqft_m2 }} m²</div>
    <div class="house-rooms">Rooms: {{ house.rooms }}</div>
    <div class="house-baths">Baths: {{ house.baths }}</div>

    <div class="house-interesting">Is interesting{{ house.is_interesting }}</div>
    <div class="house-discarded">Discarded: {{ house.is_discard }}</div>
    <div class="house-seen">Seen: {{ house.has_seen }}</div>
    <div class="house-neighborhood">Neighborhood: {{ house.neighborhood }}</div>
    {% if house.address %}
        <div class="house-address">Address: {{ house.address }}</div>
    {% endif %}
    {% if house.article_update_date %}
        <div class="house-updated">Article updated at: {{ house.article_update_date }} </div>
    {% endif %}
    {% if house.updated_at %}
        <div class="house-updated">Crawler update: {{ house.updated_at }} </div>
    {% endif %}
    <div class="house-found">Found on: {{ house.created_at }} </div>
    <div class="house-description"><p>{{ house.description }}</p></div>



{% endblock content %}

house_finder/houses/templates/houses/houses_list.html
{% extends "houses/master.html" %}
{% load bootstrap3 %}
{% load querystring from django_tables2 %}
{% load title from django_tables2 %}
{% load trans blocktrans from i18n %}

{% block content %}

<form method='GET' id="house-filter">
    {{ filter.form }}
    <input type='submit' value='Filter' />
    |
    Displaying {{ filter.qs.count }} of {{ filter.queryset.count }} items.
    |
    <a href='{{ request.path }}' >Clear</a>
</form>

{% if table.page %}
  <div class="table-container">
{% endif %}

{% block table %}
    <div class="table-responsive" id="houses-tables">
        <table class="table table-hover table-bordered table-striped"{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
            {% block table.thead %}
            <thead>                 
                <!--<tr>-->
                    <!--<th><a href="{% url "houses:index" %}" class="btn btn-small btn-primary dark"><span class="hidden-phone"><i class="fa fa-user-plus"></i> Add house</span></a>-->
                      <!---->
                    <!--</th>                  -->
                    <!--<th colspan="5">                                         -->
                        <!--<form method="post" class="form-inline form-search pull-right">-->
                          <!--{% csrf_token %}-->
                            <!--<div>-->
                              <!--<input id="search_form_id" name="search" type="text" class="form-control col-md-3" placeholder="House data"{% if search %} value="{{ search }}"{% endif %}>-->
                              <!--<button type="submit" class="btn btn-small btn-dark"><i class="fa fa-search"></i> Search</button>-->
                            <!--</div>              -->
                        <!--</form>-->
                    <!--</th>                  -->
                <!--</tr>-->
             
              <tr>
                {% for column in table.columns %}
                    {% if column.orderable %}
                    <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header|title }}</a></th>
                    {% else %}
                    <th {{ column.attrs.th.as_html }}>{{ column.header|title }}</th>
                    {% endif %}
                {% endfor %}
              </tr>
            </thead>
            {% endblock table.thead %}
            {% block table.tbody %}
            <tbody>
                {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                  {% block table.tbody.row %}
                  <tr class="{% cycle "odd" "even" %}">
                      {% for column, cell in row.items %}
                          <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                      {% endfor %}
                  </tr>
                  {% endblock table.tbody.row %}
                {% empty %}
                  {% if table.empty_text %}
                  {% block table.tbody.empty_text %}
                  <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                  {% endblock table.tbody.empty_text %}
                  {% endif %}
                {% endfor %}
            </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            <tfoot></tfoot>
            {% endblock table.tfoot %}
        </table>
    </div>
{% endblock table %}

{% if table.page %}
    {% block pagination %}
        {% bootstrap_pagination table.page url=request.get_full_path %}
    {% endblock pagination %}
  </div>
{% endif %}


{% endblock content %}

house_finder/houses/templates/houses/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if houses %}
    <ul>
    {% for house in houses %}
        <li><a href="{% url 'houses:detail' house.id %}">{{ house.title }}, {{ house.price }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No houses are available.</p>
{% endif %}
</body>
</html>

house_finder/houses/templates/houses/master.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html>
<head>
    <meta charset="utf-8">
    <title>House finder | {% block title %}Página principal{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
    <div id="header">
        {% block header %}
            <nav class="navbar navbar-inverse">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'houses:index' %}">House list</a>
                </div>
            </nav>
        {% endblock %}
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <footer class="footer">
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>